### ISSUE TITLE
Prevent docker-compose write output when no erros occur

### ISSUE THREAD

**Issue by Someone0nEarth** [Someone0nEarth/bwackup#8]
A silent (successful) run is very useful when using rsnapshot, so you will receive an email notification only, when an error occurred.

docker-compose has no option for a silent run and also logging everything to stderr  ( https://github.com/docker/compose/issues/7346 ), which is even more annoying.

**Comment by fede843** [comment]
Hi, try using chronic https://github.com/docker/compose/issues/5296#issuecomment-1124906570

**Comment by Someone0nEarth** [comment]
> Hi, try using chronic [docker/compose#5296 (comment)](https://github.com/docker/compose/issues/5296#issuecomment-1124906570)

I will have a look on that! Thx!
